# General, there may only be one; the general is the main build every build inherits from general
[[General]]
Name = "hello"
Build = "debug"

# FlagGroups, have a name and can reference other Flag groups
[[FlagGroup]]
Name = "general"
Flags = ["-Wall", "-Wextra", "-std=c99"]

[[FlagGroup]]
Name = "debug"
Flags = ["-g"]
FlagGroups = ["general"]

[[FlagGroup]]
Name = "release"
Flags = ["-O3", "-march=native", "-mtune=native"]
FlagGroup = "general"

# Builds have a name and can reference other builds from that, inehert values from referenced build
[[Build]]
Name = "general"
Type = "exe"
Target = "hello.out"
FlagGroup = "general"

[[Build]
Name = "debug"
Build = "general"
FlagGroup = "debug"

[[Build]]
Name = "release"
Build = "general"
FlagGroup = "release"
Target = "release.out"
Exclude = ["not/*.c"]

[[Source]]
Path = "main.c"
Flags = ["-DEEZNUTS=1"]

[[Source]]
Path = "*.c"

[[Test]]
Execute = "./"

[[Dependency]]
Source = "<link>@commit0"
Name = commit0

[[Dependency]]
Source = "<link>@commit1"
Name = commit1
